### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#110]
Separate Japanese texts into a "language file" so that translation and switching to another language would be easy.
I want to start from making a language file for the core game part.

- [x] Rewrite server/rpc/game/game.coffee and make language files
- [x] Test language files

**Comment by uhyo** [comment]
As is a big change, it will be developed in the branch https://github.com/uhyo/jinrou/tree/issue/110/i18n

**Comment by uhyo** [comment]
:tada: All Japanese texts have been kicked out of server/rpc/game/game.coffee.
Now I'm going to manually test all roles.

**Comment by mm018347** [comment]
Diviner & SantaClaus & Thief & SeersMama & Emma
これらも少し小さいミス。

https://github.com/mm018347/jinrou/commit/29aa55548a2ad7ac040d532f5f19e3109b32084f
https://github.com/mm018347/jinrou/commit/cf30f507fe897d2a28fd9ec3fc928bc953fb587a
https://github.com/mm018347/jinrou/commit/d3b173fd59d59458caea2c911103d864b6ecc1e3

**Comment by mm018347** [comment]
Ushinotokimairi
https://github.com/mm018347/jinrou/commit/1bd087276c3ccf61bf8b2fcd2b1be6059cc89c10

**Comment by uhyo** [comment]
I cherry-picked some of your commits.
But I cannot approve the changes to SantaClaus,
as it makes the code inconsistent with the Japanese language file.

**Comment by mm018347** [comment]
このようにですか？
https://github.com/mm018347/jinrou/commit/d48681c7380aabe95994a5b658b363fe1c5aebe6

**Comment by uhyo** [comment]
thingが正しく表示されないんですね、気づきませんでした。
それならこれで行こうと思います。

**Comment by mm018347** [comment]
Sorcerer
https://github.com/mm018347/jinrou/commit/a9339af4e5365d2a17bedee272ff9e043b93f6e8

**Comment by Sunev** [comment]
@mm018347 
Why not open a pull request directly? I think this will be more convenient for everyone.
为什么不直接开启一个pull request呢？ 我觉得这对大家来说会更方便。

**Comment by mm018347** [comment]
@Sunev 
わかる。
私はすでに提出しました、すみません。
明白。
刚刚稍微摸索了一下，我已经开启了，不好意思。

**Comment by mm018347** [comment]
FortuneResultのpumkpin、正確にはpumpkin。

Liarを占いの時にこのミストリガ、わからない。
[Liar.txt](https://github.com/uhyo/jinrou/files/1638279/Liar.txt)
http://cheshire.pinomeng.com:85/room/3531

	
WanderingGuard.noGuardMode
現れたことが一度、その後は正常で、原因不明。
http://cheshire.pinomeng.com:85/room/3504

**Comment by Sunev** [comment]
Also in [the above room](http://cheshire.pinomeng.com:85/room/3531), [```Liar.select```](https://github.com/mm018347/jinrou/blob/taiwan/language/tw/roles.yaml#L213) gives 
>輝夜月(貓爪) 對 慢心丸 占卜。, 'target': 慢心丸 })

while it should be 
>輝夜月(貓爪) 對 慢心丸 占卜。

**Comment by uhyo** [comment]
The Liar bug might have originated from i18next.
I might have to reconsider use of it.

**Comment by uhyo** [comment]
I fixed all the bugs listed above.
I review it once again and then merge it.

**Comment by uhyo** [comment]
merged!
