### ISSUE TITLE
Security hole in just-in-time login

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#117]
https://twitter.com/hatimitu_wolf/status/942684001877164033

**Comment by uhyo** [comment]
But it does not reproduce for me...

**Comment by Sunev** [comment]
日本語はあまりにも難しい。
Well, I would like to take this report as a false alarm, since the following description is wrong.
> ON: その入り方だとIP参照されないってだけだから対策されてる可能性はある 2017-12-17 20:39:14

```util.loginWindow``` acts as same as logging from homepage.

**Comment by uhyo** [comment]
Hmm, I think so too.
Currently the expiry is not shown to a user, so he may have taken expiration as just passing through the security.
