### ISSUE TITLE
Divine bug?

### ISSUE THREAD

**Issue by mm018347** [uhyo/jinrou#126]
![mstsc_2018-01-06_01-59-49](https://user-images.githubusercontent.com/19428719/34621760-5efebf68-f285-11e7-89db-28446c343867.png)
![mstsc_2018-01-06_02-01-52](https://user-images.githubusercontent.com/19428719/34621819-98a91b50-f285-11e7-9ea7-47644b417304.png)
http://cheshire.pinomeng.com:85/room/3389
3日目夜→4日目日起こる

**Comment by Sunev** [comment]
I'm a little confused, as there is no ApprenticeSeer appeared in that game.
Is the code on your server up-to-date with 4b1001369c530f4848f8c320ca76f7ddeaba34fc ?

**Comment by mm018347** [comment]
Although not the latest content, but the difference is not much.

This is the latest:
https://github.com/mm018347/jinrou/commit/f270e8aeec7a4a674b77bd9bd3b95ea48ebca68b

**Comment by uhyo** [comment]
`Watching.Diviner.sunrise` in the stack trace is quite strange, and is a big hint here.
The player named 雨 is in a strange state, where he is both a Watching and a PI at the same time.
I think `game.participants` has two records for this player,
which is the true character of this bug.

Then, the duplicate log "雨 中途加入房間。" is indicating the actual error, wrong handling of duplicate entry requests.

**Comment by uhyo** [comment]
We have to add a check in `server.rooms.join` to prevent this bug.
