### ISSUE TITLE
“女王観戦者”or“女王感染者”？

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#13]
Just found this line:
x.die game,"hinamizawa"
Is “女王観戦者” kind of misspelling？

**Comment by uhyo** [comment]
This role originates in the same role in the 桃栗 server (http://www7a.biglobe.ne.jp/~kuri/jinro_rule2011.htm ).
So this is correct; even though I don't know wheter the origin derives from misspelling or not.

**Comment by Sunev** [comment]
Thank you very much. Learned a lot from here (http://wikiwiki.jp/gekkajinro/).
