### ISSUE TITLE
変化役職 in ケミカル人狼

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#140]
変化役職 behaves weirdly in ケミカル人狼

> ケミカル人狼で、◯◯×ドッペルゲンガーの状態でドッペル対象者(役職：△△×◇◇)が死亡した際、◯◯×△△ではなく、△△×ドッペルゲンガーとなる。人狼占いによる狂人変化でも同様のことが起こる。
> また、ケミカル人狼において、サイコキラーを能力対象に選択しても死亡しないとの情報がある。

**Comment by Sunev** [comment]
Does this imply that every sub job needs a GUID?

**Comment by uhyo** [comment]
I have not looked into it yet, but using GUIDs would be a nice solution.

**Comment by uhyo** [comment]
Maybe related: https://twitter.com/R1012345678/status/983021536197017600
