### ISSUE TITLE
No result for copy 忍者

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#143]
https://jinrou.uhyohyo.net/room/122527

**Comment by uhyo** [comment]
`@flag` is not prepared for copied 忍者. It should be moved into `Game`'s property?

**Comment by Sunev** [comment]
If we take it as a bug, this seems to be the easiest way to handle it.
I personally tend to treat it as an exception—Ninja born at night cannot use skills immediately.
```Ninja.sleeping:->@target? || !@flag?```

**Comment by uhyo** [comment]
IMO I don't want to make an exception, as inconsistency makes users confused.
