### ISSUE TITLE
About icons' link which finally falls back to HTTP

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#144]
As we know, some users' avatars are stored on servers that do not support https.
I recently noticed that each time when sunrise, sunset and player commented, these links will try to upgrade to https.
Is there any way to make this upgrade acts only once in a single room?

**Comment by uhyo** [comment]
Nice catch!
I'm planning to somehow fix it. The simplest way is to cache result of upgrading for each URL, but cache may grow for a long-running browser tab.
