### ISSUE TITLE
Guard and 催眠術師

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#161]
https://twitter.com/R1012345678/status/1015624537210159105

**Comment by Sunev** [comment]
No, this bug have nothing to do with Hypnotist, it's because 
``````
class Dog extends Player
    midnightSort:100

class Vampire extends Player
    midnightSort:100
``````
What about to decrease Dog's midnightSort to 80 or 81?

**Comment by uhyo** [comment]
Oh, thanks.
Changing it to 80 would be good.
