### ISSUE TITLE
scapegoat votes too fast

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#163]
Scapegoat could vote before players suicide.

**Comment by Sunev** [comment]
Because [```pl.votestart```](https://github.com/uhyo/jinrou/blob/bcbfb5573efcfad57b61c93e935815362d347246/server/rpc/game/game.coffee#L1289) comes out earlier than [```@bury "other"```](https://github.com/uhyo/jinrou/blob/bcbfb5573efcfad57b61c93e935815362d347246/server/rpc/game/game.coffee#L1318)

**Comment by uhyo** [comment]
I checked that `@bury "other"` can come before votestart.
