### ISSUE TITLE
Priest's guard didn't work

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#178]
https://twitter.com/hakoniwawind/status/1023028590374346752
https://jinrou.uhyohyo.net/room/128628

**Comment by uhyo** [comment]
Its cause is still completely unknown, hard to uncover.
I leave it unattended until similar bug is reported.

**Comment by Sunev** [comment]
How this player's data looks like in ```db.games.players```?
Is it like 
``````
[{
    Complex_main:{
        Complex_main:{
            Complex_main:{
                type:"Patissiere"
            },
            Complex_sub:{
                type:"Hunter"
            },
            Complex_type:"Chemical"
        },
        Complex_sub:null,
        Complex_type:"HolyProtected"
    },
    Complex_sub:null,
    Complex_type:"Friend",
}]
``````

**Comment by uhyo** [comment]
No, it didn't have HolyProtected at the end. It was just Friend of Chemical of Patissiere and Hunter.
I guess HolyProtected was somehow removed during the game, or the Priest failed to attach HolyProtected at the first night.

**Comment by uhyo** [comment]
https://twitter.com/hakoniwawind/status/1025906879954804736

My follower reported that a Copy canceled priest's job.

**Comment by Sunev** [comment]
Do you mean that クープロト was never actually become HolyProtected, because 【緑の狐】ロビン used Copy after Priest?
Well, that's a fantastic debug.

**Comment by uhyo** [comment]
That's true. Many roles might have been reset by Copy so far.
