### ISSUE TITLE
Chemical Bugs

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#191]
To test my merging of v1.13.3, I biult a room on my local, and it coincidentally shows some problems in one single room.
- [ ] ```Poisoner×Doppleganger``` used Doppleganger's skill to ```Spellcaster×HolyMarked```, and then became ```Spellcaster×Doppleganger```, instead of ```Poisoner×Spellcaster```, after target dead.

- [x] Both ```Spellcaster×HolyMarked``` and ```Cursed×Diviner``` touched ```PsychoKiller×EyesWolf(Decider, MinionSelector)```, but neither of them got killed by PsychoKiller.

- [x] ```Diviner×Stalker``` stalked after ```Spellcaster×HolyMarked```, and get system log "debug6 stalked after debug3(Spellcaster×HolyMarked)". Yet while ```PsychoKiller×EyesWolf(Decider, MinionSelector)``` choosing ```Diviner×Stalker``` as a WolfMinion, he could only get to know target's job on leftside, "	debug5 selected debug6 (Diviner) as a WolfMinion。"

- [x] The last bug I met is a familiar one. While room rule of DeathNote is "yes", and any of Werewolf series just get the DeathNote in some night. He will : 1. Never got konwn that his getting the DeathNote before he Bite somebody. 2. Cannot use the DeathNote after the bite by getting MsgBox saying "Skill already used"

**Comment by uhyo** [comment]
I fixed these bugs but the first one. Let me fix it after I implement GUIDs.

**Comment by Sunev** [comment]
The 1st bug is as same as #140 . 
I suddenly came up with such an idea, Doppleganger is designed to hide himself as a sub job after first acting.
A flag of first action would help Doppleganger to make it to be sub of its own.
Would this help?

**Comment by uhyo** [comment]
Yeah, a first action flag would be needed.

**Comment by uhyo** [comment]
oops, commit message was wrong.
