### ISSUE TITLE
Priority of monologue in Chemical

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#228]
要望：
ケミカル人狼において、右側人狼系だと狼の遠吠えよりも独り言が優先されてしまう。

左右の役が何であれ、
①狼の遠吠え＞共有者の小声≧叫迷狂人の小声≧妖狐の念話＞独り言　のように優先度の変更を希望。
②狼の遠吠えと独り言の区別がつきづらいため、どちらか色の変更を希望。

**Comment by uhyo** [comment]
closed by c7d8f98
