### ISSUE TITLE
Advices and Bug Reporting for Chemical Werewolf

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#23]
First of all, thank you very much for developing Chemical Werewolf. It is so attractive that my friends and I just spent a whole night on it. Yet, it seems exist something would make players confused and some bugs those I cannot handle with.
Advices:
 1.	 Players found confused about which team they belong to. Should we add some instruction about their teams into div#jobinfo?

 2.	 Now div#jobinfo displays job information like "You are A×B(Details of B·Details of A)". If we could change that into "You are A×B(Details of A·Details of B)", I think it would make players feel better.

Bugs:
 1.	 For some job whose skill could be used every night (e.g. Diviner, Guard, WolfDiviner), which I named as A. If a player get a Chemical Werewolf as 「A×A」, that skill of A could be used for unlimited times during one night.
1.1.	 If that skill of A could cause Sudden Death (gone-night), it will.
1.2.	 Exceptions to Vampire, 「Vampire×Vampire」 can attack for only once, and then gone-night.
1.3.	 Exceptions to Cat, 「Cat×Cat」 can revive some others for twice normally without gone-night.
1.4.	 「Werewolf×Werewolf」 can attacks others normally, as there exists the counter of werewolf_target_remain.
1.5.	 For those jobs whose night skill could be used for only once (e.g. Bomber), they behave normally.

 2.	 For some job with passive skill (e.g. Prince, ToughGuy) token as A. A's passive skill would never acts if A becomes a sub job. For example:
2.1.	 If a player becomes  「Something×Prince」, the player could be hanged after first voted.
2.2.	 If a player becomes  「Something×ToughGuy」, the player will die after attacked by Werewolf.
2.3.	 Anyone touched 「Others×PsychoKiller」 won't die, while those touched 「PsychoKiller×PsychoKiller」 will die normally

 3.	 「Others×QueenSpectator」 will lead to a situation that nobody can see the Tip like “Someone is QueenSpectator”, even the QueenSpectator herself, which is dangerous; 「QueenSpectator×Others」 is kind of visible but still comes with limit:
Let us take some job of Human Team as H, and some job out of Human Team as N. Players like 「H×N」 can identify the QueenSpectator and those like 「N×H」 cannot, while QueenSpectator should not be visible to both of them. Normally, we assert that only players like 「H×another H」 could make sure who is the QueenSpectator.

 4.	 In some situation, which I have not make sure how to repeat, BadLady(X) proposed to someone(Y), then Y became a lonely Friend, instead of Friend of X. In that situation, Y gets instruction at div#jobinfo like “Friends are Y” instead of “Friends are X, Y”, while X gets “Friends are X, Y”. More than that, Y would not suicide if X died but X would.

**Comment by uhyo** [comment]
Thank you for your advice and very much detailed bug reports. Your reports are highly expressive and equipped with great reproducability. I really appreciate it.
I'm now working on the bugs and other enhancements.

**Comment by uhyo** [comment]
Now all the bugs seem to be fixed. Your advices are also implemented.
Thank you very much.
