### ISSUE TITLE
When everyone suddenDeath, it will be Draw

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#233]
要望：
生存者なしになって引き分け処理になった場合、突然死した人も引き分け扱いになっているのですが、
その場合でも突然死した人だけ敗北判定を希望します。

ちなみに、量子人狼では希望通り、敗北となっていました。
https://jinrou.uhyohyo.net/room/129990

**Comment by q6771020** [comment]
Hi

**Comment by q6771020** [comment]
1231231313qweqweqwe
