### ISSUE TITLE
蘇生時の結果表示

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#238]
https://jinrou.uhyohyo.net/room/132172
2日目の夜に占い師が死亡→4日目昼に蘇生するが、そのときに2日目の占い結果が表示されている。
恐らく、アイドルや超常現象研究者などの朝一結果が出る役職も同様に起こりそう？

夜の能力は死亡しても効果が発動することから、仕様でも良い気はします。
ただし、それなら死亡時結果隠されるのはなあ。という思いもあります。

**Comment by uhyo** [comment]
closed by d3c699e
