### ISSUE TITLE
恋人＞カルトリーダー in Chemical

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#240]
https://jinrou.uhyohyo.net/room/132323
ケミカル人狼で、カルトリーダーが恋人になった場合の勝利判定

ドキュメントでは、以下となっています。
勝利条件
陣営は、自分の2つの役職のうち、優先順位の高い方の陣営になります。優先順位は高い方から以下の順です。
1.カルトリーダー
2.恋人陣営

カルトリーダーが恋人になった場合、信者から外れるため、恋人勝利になるところは良いですが、
ドキュメントを見る限り、カルトリーダーは敗北なのでは？
ただし、ケミカルじゃないときはカルトリーダーが恋人になった場合、恋人で勝っていたケースを見たことがあるため（カルト勝利フラグは満たしていない）、
ドキュメント側の優先順位を1⇔2逆転させるだけで済みそうです。
（勝利判定ページの、複数の陣営が条件を満たしているときの優先順位から引っ張ってきている？）

**Comment by uhyo** [comment]
役職「カルトリーダー×狼の子」の陣営はカルトリーダー陣営ですが、
恋人は陣営と勝利条件を上書きするため「恋人（カルトリーダー×狼の子）」は恋人陣営で勝利条件も恋人勝利になります。

**Comment by hakoniwawind** [comment]
そうすると、2つの役職のうち恋人よりカルトリーダーが優先されるケースは、「カルトリーダー×求愛者」のように元々恋人陣営保持していなければならないということですかね？

**Comment by uhyo** [comment]
そのとおりです。
