### ISSUE TITLE
SantaClaus isWinner in Chemical

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#253]
質問：
https://jinrou.uhyohyo.net/room/132674
サンタクロースが村去ってももう片方の陣営が優先されて敗北しているケースを確認。

ケミカル人狼のドキュメントでは、「自分の陣営と一致する役職の勝利条件のみ適用されます。」とあるので仕様でしょうか？
（サンタクロースは特殊勝利条件を持つが、あくまで村人陣営なので。）

**Comment by uhyo** [comment]
ドキュメントに書いてあるとおりの挙動ではありますが、あまり良くないので直したいですね。
