### ISSUE TITLE
量子人狼 bug

### ISSUE THREAD

**Issue by mm018347** [uhyo/jinrou#257]
![image](https://user-images.githubusercontent.com/19428719/45266041-8f25bd80-b487-11e8-8210-52d61f79d10f.png)

rule.rules.get('uuantumwerewolf_diviner') === 'on' ? (
↓
rule.rules.get('quantumwerewolf_diviner') === 'on' ? (

**Comment by hakoniwawind** [comment]
https://jinrou.uhyohyo.net/room/132799
報告しようと思いましたが、占い師の結果も表示=ONなので、恐らくこれに該当してますね。
