### ISSUE TITLE
死体の表示順

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#265]
https://jinrou.uhyohyo.net/room/133039
初日、狐憑きが怪盗に盗まれて消失し、冒涜者が後追い自殺。
ただし、このときの自殺ログは、パン屋やトラブルメーカーの後に出ていて、
マニュアルの「人狼の噛みと呪殺などにより死体が2つ以上発生した場合は、その表示順はランダムです。」にそぐわない。

これはもう仕様上仕方ないと思いますが、一応報告です。

**Comment by uhyo** [comment]
怪盗の役職変化タイミングが変なのが問題なので、sunriseからmidnightに変更します。

**Comment by hakoniwawind** [comment]
妖狐を盗んだ場合、同時に占いされると呪殺は起きなかったため、
midnightsortに移すならば、人狼占いよりも遅めのほうが良さそうです。
一点気になるのは、アイドル結果でしょうか。
人外を盗んだ場合は、怪盗→人外、人外は盗まれる前として数が計算されていました。（村-1）
盗んだあとに結果表示は変わらないので、多分問題ないと考えていますが。。
