### ISSUE TITLE
襲撃耐性消失

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#275]
https://jinrou.uhyohyo.net/room/133610
3日目の夜、人狼が自らを襲撃して襲撃が成功する。
2日目の夜も同様に自らを襲撃しているがそちらは問題なく失敗している。

**Comment by uhyo** [comment]
これはフランケンシュタインの怪物が占い師を吸収しており、それを人狼占いで占ったことにより発生した逆呪殺です。
