### ISSUE TITLE
謎の死

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#276]
https://jinrou.uhyohyo.net/room/133611
最終夜、3人謎の死を遂げている…。何もされていないアカウントも死亡。

**Comment by uhyo** [comment]
3人の死因はプレイヤー「妖狐」の中に存在した女王観戦者が死亡したことです。
（フランケンシュタインの怪物が吸収した役職が狂人変化する問題は #274 で対応。）
