### ISSUE TITLE
BloodyMary bug

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#28]
BloodyMary's night skill will not work when BloodyMary is ```class Complex```.
1. Once ```$("#jobform")``` of BloodyMary is submitted, it would be reset immediately like there was nothing happened after the click. Player cannot get a ```splashlog```, nor a Error alert at this time.
2. But it was submitted normally, as it got logged into ```db.games→gamelogs```, like
```
                {
                        "id" : "A",
                        "type" : "BloodyMary",
                        "target" : "B",
                        "event" : "job",
                        "flag" : null,
                        "day" : 5
                },
```
And this log may appear for multiple times, if the player tried that.

**Comment by uhyo** [comment]
Good issue!
Thanks.
