### ISSUE TITLE
CraftyWolf bug

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#280]
https://jinrou.uhyohyo.net/room/133649
2日目の夜、狡猾な狼が死んだふりをするが、
昼になったログが優先されて、投票時に突然死する。
（発言的に、死んでいるが投票コマンドは出ていた？）

恐らく、昼になったと同時に死んだふりを選択したため、この現象が起きたのではないだろうか。

**Comment by uhyo** [comment]
原因はその通りです。
#273 を修正したら一緒に直りました。
