### ISSUE TITLE
isWinner in Chemical

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#282]
https://jinrou.uhyohyo.net/room/133749
勝利判定について。
人狼陣営が勝利したとき、以下の役も勝利している。

①一匹狼×マッドサイエンティスト
　一匹狼陣営の優先度がよくわかっていないため、仕様かもしれませんが…
　人狼陣営であるマッドサイエンティスト側で勝利している？
　（一匹狼陣営＝人狼陣営？一匹狼勝利でも勝利扱いか？）

②プリンス×ドッペルゲンガー
　ドッペルゲンガーは一度も変化に成功していないため、
　仮に身代わりくんドッペルで身代わりくんの陣営が勝利したとしても、敗北が正だと考える。

**Comment by hakoniwawind** [comment]
ちなみに、ここでも身代わりくんが狼の子生存に関わらず、襲撃権利を得ている。
（直ったと思いますが念のため。。）

**Comment by uhyo** [comment]
ドキュメントに書いていませんでしたが一匹狼陣営よりも普通の人狼陣営が優先されます。
