### ISSUE TITLE
単独陣営を隠す

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#299]
https://twitter.com/rapier_japan/status/1040954972072886272
![1111](https://user-images.githubusercontent.com/42696493/45926631-547c5480-bf60-11e8-9cc1-50c6c51ae0b5.PNG)

昔の部屋から同じ設定で立て直す～の裏技を使えばチェック出来るようになります。

**Comment by uhyo** [comment]
仕様です（配役公開をの設定を「陣営ごとの数のみ公開」にすると出現します）

**Comment by uhyo** [comment]
でもやっぱり分かりにくいので闇鍋時は常時出現にします
