### ISSUE TITLE
"node app.js" failed

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#3]
~/jinrou# node app.js
Failed to load config file.
Copy config.default/app.coffee to config/app.coffee, edit app.coffee, and retry.
[Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.]

I have already copied and edited config/app.coffee, but still failed to load config file. 

Here is my npm list:
~/jinrou# npm list
werewolf@1.10.1-9 /root/jinrou
├─┬ csv@0.4.5
│ ├── csv-generate@0.0.6
│ ├── csv-parse@0.1.3
│ ├── csv-stringify@0.0.8
│ └── stream-transform@0.1.0
├─┬ jade@1.11.0
│ ├── character-parser@1.2.1
│ ├─┬ clean-css@3.3.5
│ │ ├─┬ commander@2.8.1
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ source-map@0.4.3
│ │   └── amdefine@1.0.0
│ ├── commander@2.6.0
│ ├─┬ constantinople@3.0.1
│ │ └─┬ acorn-globals@1.0.4
│ │   └── acorn@1.2.2
│ ├─┬ jstransformer@0.0.2
│ │ ├── is-promise@2.0.0
│ │ └─┬ promise@6.1.0
│ │   └── asap@1.0.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ transformers@2.1.0
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.1
│ │ └─┬ uglify-js@2.2.5
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.3
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.0
│ ├─┬ uglify-js@2.4.23
│ │ ├── async@0.2.10
│ │ ├─┬ source-map@0.1.34
│ │ │ └── amdefine@1.0.0
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.5.4
│ │   ├── camelcase@1.1.0
│ │   ├── decamelize@1.0.0
│ │   ├── window-size@0.1.0
│ │   └── wordwrap@0.0.2
│ ├── void-elements@2.0.1
│ └─┬ with@4.0.3
│   ├── acorn@1.2.2
│   └── acorn-globals@1.0.4
├─┬ mongodb@2.0.36
│ ├── es6-promise@2.1.1
│ ├─┬ mongodb-core@1.2.4
│ │ ├── bson@0.4.7
│ │ └─┬ kerberos@0.0.12
│ │   └── nan@1.8.4
│ └─┬ readable-stream@1.0.31
│   ├── core-util-is@1.0.1
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
├─┬ ntwitter@0.5.0
│ ├── cookies@0.1.6
│ └── keygrip@0.2.4
├── oauth@0.9.13
├─┬ socketstream@0.4.3
│ ├── apitree@1.2.0
│ ├── async@0.9.0
│ ├─┬ body-parser@1.12.0
│ │ ├── bytes@1.0.0
│ │ ├── content-type@1.0.1
│ │ ├─┬ debug@2.1.3
│ │ │ └── ms@0.7.0
│ │ ├── depd@1.0.1
│ │ ├── iconv-lite@0.4.7
│ │ ├─┬ on-finished@2.2.1
│ │ │ └── ee-first@1.1.0
│ │ ├── qs@2.3.3
│ │ ├── raw-body@1.3.3
│ │ └─┬ type-is@1.6.4
│ │   ├── media-typer@0.3.0
│ │   └─┬ mime-types@2.1.2
│ │     └── mime-db@1.14.0
│ ├─┬ chokidar@0.12.6
│ │ ├── async-each@0.1.6
│ │ └─┬ readdirp@1.3.0
│ │   ├── graceful-fs@2.0.3
│ │   ├─┬ minimatch@0.2.14
│ │   │ ├── lru-cache@2.6.5
│ │   │ └── sigmund@1.0.1
│ │   └─┬ readable-stream@1.0.33
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ clean-css@2.2.22
│ │ └── commander@2.2.0
│ ├── colors@1.0.3
│ ├── commander@2.6.0
│ ├─┬ compression@1.4.1
│ │ ├─┬ accepts@1.2.10
│ │ │ ├─┬ mime-types@2.1.2
│ │ │ │ └── mime-db@1.14.0
│ │ │ └── negotiator@0.5.3
│ │ ├── bytes@1.0.0
│ │ ├─┬ compressible@2.0.4
│ │ │ └── mime-db@1.14.0
│ │ ├─┬ debug@2.1.3
│ │ │ └── ms@0.7.0
│ │ ├── on-headers@1.0.0
│ │ └── vary@1.0.1
│ ├─┬ connect@3.3.4
│ │ ├─┬ debug@2.1.3
│ │ │ └── ms@0.7.0
│ │ └─┬ finalhandler@0.3.3
│ │   └─┬ on-finished@2.2.1
│ │     └── ee-first@1.1.0
│ ├─┬ connect-redis@2.0.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ └── redis@0.10.3
│ ├─┬ connect-static@1.4.0
│ │ ├── findit2@2.2.3
│ │ ├── mime@1.2.11
│ │ ├── pend@1.2.0
│ │ └── streamsink@1.2.0
│ ├─┬ cookie-parser@1.3.4
│ │ ├── cookie@0.1.2
│ │ └── cookie-signature@1.0.6
│ ├─┬ cookie-session@1.1.0
│ │ ├─┬ debug@2.1.3
│ │ │ └── ms@0.7.0
│ │ └── on-headers@1.0.0
│ ├─┬ cookies@0.5.0
│ │ └── keygrip@1.0.1
│ ├─┬ csurf@1.7.0
│ │ ├── cookie@0.1.2
│ │ ├── cookie-signature@1.0.6
│ │ ├─┬ csrf@2.0.7
│ │ │ ├── base64-url@1.2.1
│ │ │ ├── rndm@1.1.0
│ │ │ ├── scmp@1.0.0
│ │ │ └─┬ uid-safe@1.1.0
│ │ │   └── native-or-bluebird@1.1.2
│ │ └─┬ http-errors@1.3.1
│ │   ├── inherits@2.0.1
│ │   └── statuses@1.2.1
│ ├─┬ engine.io@1.5.1
│ │ ├── base64id@0.1.0
│ │ ├─┬ debug@1.0.3
│ │ │ └── ms@0.6.2
│ │ ├─┬ engine.io-parser@1.2.1
│ │ │ ├── after@0.8.1
│ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ ├── blob@0.0.2
│ │ │ ├─┬ has-binary@0.1.5
│ │ │ │ └── isarray@0.0.1
│ │ │ └── utf8@2.0.0
│ │ └─┬ ws@0.5.0
│ │   ├── nan@1.4.3
│ │   ├── options@0.0.6
│ │   └── ultron@1.0.2
│ ├── escape-html@1.0.1
│ ├── eventemitter2@0.4.14
│ ├─┬ express-session@1.10.2
│ │ ├── cookie@0.1.2
│ │ ├── cookie-signature@1.0.5
│ │ ├── crc@3.2.1
│ │ ├─┬ debug@2.1.3
│ │ │ └── ms@0.7.0
│ │ ├── depd@1.0.1
│ │ ├── on-headers@1.0.0
│ │ └─┬ uid-safe@1.0.3
│ │   ├── base64-url@1.2.0
│ │   └── native-or-bluebird@1.1.2
│ ├── parseurl@1.3.0
│ ├── redis@0.12.1
│ ├── semver@4.3.3
│ ├─┬ send@0.11.0
│ │ ├── debug@2.1.3
│ │ ├── depd@1.0.1
│ │ ├── destroy@1.0.3
│ │ ├─┬ etag@1.5.1
│ │ │ └── crc@3.2.1
│ │ ├── fresh@0.2.4
│ │ ├── mime@1.2.11
│ │ ├── ms@0.7.0
│ │ ├─┬ on-finished@2.2.1
│ │ │ └── ee-first@1.1.0
│ │ └── range-parser@1.0.2
│ ├─┬ serve-favicon@2.2.0
│ │ ├─┬ etag@1.5.1
│ │ │ └── crc@3.2.1
│ │ ├── fresh@0.2.4
│ │ └── ms@0.7.0
│ ├─┬ serve-static@1.6.5
│ │ └─┬ send@0.9.3
│ │   ├── debug@2.0.0
│ │   ├── depd@0.4.5
│ │   ├── destroy@1.0.3
│ │   ├─┬ etag@1.4.0
│ │   │ └── crc@3.0.0
│ │   ├── fresh@0.2.4
│ │   ├── mime@1.2.11
│ │   ├── ms@0.6.2
│ │   ├─┬ on-finished@2.1.0
│ │   │ └── ee-first@1.0.5
│ │   └── range-parser@1.0.2
│ ├── shortid@2.2.2
│ ├── uglify-js@1.3.3
│ ├── uid2@0.0.3
│ └── utils-merge@1.0.0
├─┬ ss-clientjade@0.0.7
│ ├─┬ jade@1.0.2
│ │ ├── character-parser@1.2.0
│ │ ├── commander@2.0.0
│ │ ├── constantinople@1.0.2
│ │ ├── mkdirp@0.3.5
│ │ ├─┬ monocle@1.1.50
│ │ │ └─┬ readdirp@0.2.5
│ │ │   └─┬ minimatch@2.0.8
│ │ │     └─┬ brace-expansion@1.1.0
│ │ │       ├── balanced-match@0.2.0
│ │ │       └── concat-map@0.0.1
│ │ ├─┬ transformers@2.1.0
│ │ │ ├─┬ css@1.0.8
│ │ │ │ ├── css-parse@1.0.4
│ │ │ │ └── css-stringify@1.0.5
│ │ │ ├─┬ promise@2.0.0
│ │ │ │ └── is-promise@1.0.1
│ │ │ └─┬ uglify-js@2.2.5
│ │ │   ├─┬ optimist@0.3.7
│ │ │   │ └── wordwrap@0.0.3
│ │ │   └─┬ source-map@0.1.43
│ │ │     └── amdefine@1.0.0
│ │ └─┬ with@2.0.0
│ │   └─┬ uglify-js@2.4.0
│ │     ├── async@0.2.10
│ │     ├─┬ optimist@0.3.7
│ │     │ └── wordwrap@0.0.3
│ │     ├─┬ source-map@0.1.43
│ │     │ └── amdefine@1.0.0
│ │     └── uglify-to-browserify@1.0.2
│ └─┬ uglify-js@2.4.23
│   ├── async@0.2.10
│   ├─┬ source-map@0.1.34
│   │ └── amdefine@1.0.0
│   ├── uglify-to-browserify@1.0.2
│   └─┬ yargs@3.5.4
│     ├── camelcase@1.1.0
│     ├── decamelize@1.0.0
│     ├── window-size@0.1.0
│     └── wordwrap@0.0.2
├─┬ ss-jade@0.1.3
│ └─┬ jade@0.27.7
│   ├── coffee-script@1.4.0
│   ├── commander@0.6.1
│   └── mkdirp@0.3.5
├─┬ ss-latest-coffee@0.1.3
│ └── coffee-script@1.9.3
└─┬ ss-stylus@0.1.9
  ├─┬ nib@1.0.4
  │ └─┬ stylus@0.45.1
  │   ├── css-parse@1.7.0
  │   ├─┬ debug@2.2.0
  │   │ └── ms@0.7.1
  │   ├─┬ glob@3.2.11
  │   │ ├── inherits@2.0.1
  │   │ └─┬ minimatch@0.3.0
  │   │   ├── lru-cache@2.6.5
  │   │   └── sigmund@1.0.1
  │   ├── mkdirp@0.3.5
  │   └── sax@0.5.8
  └─┬ stylus@0.49.2
    ├── css-parse@1.7.0
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├─┬ glob@3.2.11
    │ ├── inherits@2.0.1
    │ └─┬ minimatch@0.3.0
    │   ├── lru-cache@2.6.5
    │   └── sigmund@1.0.1
    ├── mkdirp@0.3.5
    ├── sax@0.5.8
    └─┬ source-map@0.1.43
      └── amdefine@1.0.0

**Comment by uhyo** [comment]
Hi.

It was due to dependency problems.
The commit 0e95983934a073c483e0c0061d47c8bead657f24 may fix them, so please pull and redo `npm install`.

**Comment by Sunev** [comment]
Thank you very much. It works very well now.

**Comment by Sunev** [comment]
Thank you very much. It works very well now.

**Comment by Sunev** [comment]
Thank you very much. It works very well now.
