### ISSUE TITLE
エンドレス闇鍋

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#304]
要望：
エンドレス闇鍋時は、常に霊界表示なしに出来ませんか？
人狼や他の役職を知った人が転生して、告発出来てしまうため。

**Comment by Sunev** [comment]
What about to add a confirm box like " Are you sure to start this room with Heaven View on?"

**Comment by hakoniwawind** [comment]
提案するならば、以下を考えていました。

常に有り、無し　⇒　今のまま
有り　⇒　蘇生する可能性がある場合　＋　エンドレス闇鍋時

-------------------------------------------------------------------
デフォルトが「霊界表示：有り」のため、そのまま開始してしまい、止むを得ず蘇生辞退押してもらうみたいな流れがありました。
あとは…身代わりくんが転生対象になってしまう点でしょうか。
こちらは否定的な意見聞きませんが、転生後は身代わりくんも人外となる可能性あるので厄介です。
