### ISSUE TITLE
怪盗の処理

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#311]
https://jinrou.uhyohyo.net/room/134322
以下、報告します。

①怪盗が怪盗を盗んだ場合
以前は、怪盗A→怪盗Bを盗む、怪盗B→hogeを盗んだ場合
　　　　　怪盗A：怪盗→hoge、怪盗B：怪盗→hoge→怪盗
　　　　　hoge、怪盗Bが盗まれたことがわかるのはどちらも2日目夜だったはず。
　　　　　（過去ログ見つからないため、定かではないですが...）

②怪盗が2日目以降に盗むことが出来てしまっている
　ドキュメントでは「初日の夜に参加者から1人選び、その人と役職を交換します。」とある。

**Comment by hakoniwawind** [comment]
月下wikiを見たら、
>怪盗が「まだ盗んでいない怪盗」を盗んだ場合には、次の夜にもう一度盗むことができる。

と記述されていたので、怪盗A、Bの選択順序によって両方起こり得る可能性があります。。。

**Comment by uhyo** [comment]
②は仕様です（ドキュメントに追記します）。
①はちょっと何が問題なのかよく分かりませんでした。

**Comment by hakoniwawind** [comment]
https://jinrou.uhyohyo.net/room/134402
怪盗が怪盗を盗んだ場合、現状2通りのケースが出来てしまう。
①怪盗前の怪盗を盗む場合　②怪盗先の役職を盗む場合
