### ISSUE TITLE
占い結果

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#320]
https://jinrou.uhyohyo.net/room/134725
占い結果が翌日わかる設定で、無残な死体になったのにも関わらず、結果が表示されている。

サンタクロースによるプレゼントが該当か。
商人の占いセットでは再現せず。

**Comment by uhyo** [comment]
サンタクロースではなく鴉が原因でした。他に再現できるのは赤ずきん、トラブルメーカー、パン屋です。
