### ISSUE TITLE
聖なる力不発

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#333]
#306 で直ってそうですが、念のため。

https://jinrou.uhyohyo.net/room/135324
巫女×フランケンが老人を吸収して老衰（巫女発動中、聖職2回付与）

https://jinrou.uhyohyo.net/room/135326
聖職者×老人が老衰（聖職1回付与）
老人×老人が老衰（聖職2回付与、1回聖なる力発動）

https://jinrou.uhyohyo.net/room/135327
一匹狼×老人が老衰（聖職3回付与）

**Comment by uhyo** [comment]
#306 と一緒に修正されました。
