### ISSUE TITLE
普通配役

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#343]
https://jinrou.uhyohyo.net/room/135741
普通配役時（闇鍋以外）、配役公開固定のほうが良いと思いました。
　（出現陣営情報: 村人陣営5 人狼陣営2　・・・これだと設定ミスで闇鍋が始まったのではないかと疑ってしまうため。）
さらに、ルール上では闇鍋セーフティ設定も見えてしまっているため、信用に欠ける印象を受けました。

もしかしたら、GM機能有りで、このようなルールの見え方になっていた可能性もあります。

**Comment by uhyo** [comment]
GMありのときは闇鍋以外でも配役を隠せる機能です。
ただ闇鍋セーフティがルールに出ているのはバグですね。
