### ISSUE TITLE
フランケンシュタインの吸収能力が表示し続ける

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#353]
![default](https://user-images.githubusercontent.com/42696493/47502385-9885b080-d8a2-11e8-93b5-fee2e0f183ef.PNG)
ドッペルゲンガー→フランケンシュタインへ変化
能力を吸収した後に再度ドッペルゲンガーで何らかの役に変化した場合、
役職欄の表示が、フランケンで吸収した各種役職が残ったままになる。
（フランケン自体は消える。また吸収した役の能力は問題なく失う。）

**Comment by uhyo** [comment]
データベース内のデータがどうなっているか確認したいので、部屋のURLを教えていただけますか？

**Comment by hakoniwawind** [comment]
https://jinrou.uhyohyo.net/room/136259

**Comment by uhyo** [comment]
フランケンシュタインの怪物が吸収した能力が残るのは仕様ということにします。
（そのログでは確認する機会が無かったと思いますが、吸収後の能力も残っているはずです。）
