### ISSUE TITLE
人狼の行動ができない

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#364]
https://twitter.com/e4k2ClOqCP/status/1057293488608370688
https://jinrou.uhyohyo.net/room/136535

狡猾な狼の蘇生が無視された？

**Comment by hakoniwawind** [comment]
狡猾な狼だけで再現可能。
初回メッセージ↓
![33333](https://user-images.githubusercontent.com/42696493/47783383-e2a8df00-dd45-11e8-8d15-2903b618ea4f.PNG)

2回目以降のクリックでは、「今は能力を使用出来ません」となった。
このとき、人狼系の襲撃はコマンド自体は存在するが、猶予時間となると次の昼へ移行。（能力の任意化）
