### ISSUE TITLE
恋人複数組

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#377]
質問：
https://jinrou.uhyohyo.net/room/136729
「恋人はそれぞれ独立する」が「あり」の設定で、恋人以外の生存者がいるのにも関わらず試合が終了。
A⇔B⇔Cの恋人ペアになっているのですが、この場合は複数組として扱われていないのですか？

**Comment by uhyo** [comment]
その場合は1組として扱われます。複数組として扱われるのはメンバーがかぶっていない場合です。

**Comment by hakoniwawind** [comment]
回答ありがとうございます。
よくよく考えたら、A⇔B⇔Cだと独立なし設定と同じになりますね。
