### ISSUE TITLE
Decider Bug

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#38]
I got reported a bug that a ```Guard(Decider)```, who protected himself and got bitten by Werewolf, was found dead at sunrise. According to my tests, those Guards without Decider survives normally. Is this related with [the deepest Darkness](https://github.com/uhyo/jinrou/blob/master/server/rpc/game/game.coffee#L2007)?
And please take your thesis as the most important thing. This bug does not appear very often.

**Comment by Sunev** [comment]
Or this bug is caused by #27 , when dealing with Walking Dead?

**Comment by Sunev** [comment]
Actually, I don't quite understand that why ```.mcall()``` is necessary.

**Comment by uhyo** [comment]
Couldn't reproduce this bug.
Maybe there are additional conditions required for this bug to happen.

---
`mcall` calls a method of `@main` with `this` being the `Complex` itself.
We have been trying to keep `@flag`, `@target`, `@dead` and others consistent between parent and child

**Comment by Sunev** [comment]
Tested again and found that there was sth wrong in 6adf92f8b564261d286d6766103800eb225a529f about dealing with ```.midnight()```, and which got fixed in a8e058e214c2f655f979bd6808a304bb0ab0c251 by you. I had had this test done before I merge a8e058e214c2f655f979bd6808a304bb0ab0c251 .

**Comment by Sunev** [comment]
I got it, so ```.mcall()``` is necessary for methods like ```.die()```, ```.revive()```, ```.midnight()```, but not to ```.gatherMidnightSort()```. Because ```.gatherMidnightSort()``` don't change propertys.
