### ISSUE TITLE
ルーム名表示

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#382]
ルーム名(参加人数)の表示が正しくない場合がある。（正直どうでもいいですが...）
各ブラウザによって変化したので添付致します。

↓Chrome
![chrome](https://user-images.githubusercontent.com/42696493/48345521-96518d80-e6bb-11e8-9cec-3185c4399382.PNG)

↓Firefox
![fire](https://user-images.githubusercontent.com/42696493/48345535-a49fa980-e6bb-11e8-895e-0db94656dcbb.PNG)

↓Edge（正常）
![edge](https://user-images.githubusercontent.com/42696493/48345552-ad907b00-e6bb-11e8-96df-8bce0fe7ee95.PNG)

**Comment by uhyo** [comment]
新しいUIにしたら多分大丈夫になりました。
