### ISSUE TITLE
観戦者が投票時間中に発言できない

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#390]
らしい

**Comment by hakoniwawind** [comment]
https://jinrou.uhyohyo.net/room/137441
猶予期間中に発言は可能
投票専用時間の話ならばわかりませんが…

**Comment by hakoniwawind** [comment]
各ブラウザで猶予時間での発言を確認。問題なさそう。
https://jinrou.uhyohyo.net/room/137451

**Comment by uhyo** [comment]
ありがとうございます。勘違いだったようです。
