### ISSUE TITLE
ログ膨大？最下部まで遡れない

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#393]
例えば、 https://jinrou.uhyohyo.net/room/130000 等、
ログが膨大すぎると？ログが途中で遡れなくなる。（PCモードでも）
![default](https://user-images.githubusercontent.com/42696493/48765626-dd600400-ecf5-11e8-893c-f5c91a394feb.PNG)

**Comment by Sunev** [comment]
https://www.werewolf.com.cn/room/70095
https://www.werewolf.com.cn/room/70085
https://www.werewolf.com.cn/room/70083
https://www.werewolf.com.cn/room/70081
I found some room with same problem.

**Comment by Sunev** [comment]
https://www.werewolf.com.cn/room/70000 is still not functional.

**Comment by uhyo** [comment]
This seems to happen only on Chrome.
I suspect that this is Chrome's bug.
