### ISSUE TITLE
OccultMania prefer to become Diviner while he could also become Werewolf

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#397]
Imagine a Werewolf who got a gift of Diviner set from Merchant.
In such a situation, following lines determine that the OccultMania will become a Diviner, while his target's main job is Werewolf.
``````
        if p.isJobType "Diviner"
            type="Diviner"
        else if p.isWerewolf()
            type="Werewolf"
``````
This is somewhat counterintuitive. 
Is there any good solution for this?

**Comment by uhyo** [comment]
Yes, I think the OccultMania should become a Werewolf in that case.
As we do not have "Werewolf set" for now, simply flipping the order of `if` would be fine.
(This affects the Chemical "Diviber × Werewolf" case, but I think it's acceptable.)

Alternatively, we could use `accessMainLevel` to check "min" jobs before others.
