### ISSUE TITLE
表示崩れ

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#404]
https://twitter.com/hakoniwawind/status/1065907755905499136
スマフォモードにおいて、システムログの表示が一部崩れる。
求愛されました～の赤ログや、昼の終わりなどなど。
発言等で直る。

google chromeです

**Comment by uhyo** [comment]
Google Chromeのバグだったみたいです。
とりあえず様子を見ることにします。
https://bugs.chromium.org/p/chromium/issues/detail?id=910953

**Comment by uhyo** [comment]
Chrome 73で修正されたのでcloseします。
