### ISSUE TITLE
ヴァンパイアが爆発しない

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#439]
https://jinrou.uhyohyo.net/room/138969
4日目夜、人狼とヴァンパイアの襲撃が爆弾対象に被った場合、
ヴァンパイアが死亡していない。（人狼は死亡した。）

#427 でヴァンパイアの処理が消えています。
被らなくてもヴァンパイアの襲撃だと不発しそうですね。

**Comment by uhyo** [comment]
Related https://twitter.com/kj_ysnk/status/1077593028385157120
