### ISSUE TITLE
Suggest: prevent players to rebirth immediately in EndlessYaminabe

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#504]

**Comment by Sunev** [comment]
Aeffects ```.deadsunrise()``` of Baker and Drawgirl

**Comment by Sunev** [comment]
https://github.com/Sunev/jinrou/issues/59
https://github.com/Sunev/jinrou/issues/66

**Comment by hakoniwawind** [comment]
#379 も同じ原因ですし、即転生するのをやめて、早くても1日後に転生するようなシステムでも良いかなと思いました。
エンドレス闇鍋をやる理由が、長く続けたい等‥ならば、あまりベターな変更ではありませんが。

**Comment by Sunev** [comment]
solved in 11235a0
