### ISSUE TITLE
意図しない形で村が建ってしまう

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#511]
要望：

![default](https://user-images.githubusercontent.com/42696493/53003569-93142d80-3472-11e9-9f4b-39bef28c88ac.PNG)

タイミングがとても悪いと思いますが。。
下図のようなときにエンターを押すと自動的に村が作成完了されてしまい、
それによってGM設定やら出来ずに廃村…というケースがあるみたいです。
若しくは、何らかの確認欄をつけたほうが良いかもしれません。

![default](https://user-images.githubusercontent.com/42696493/53003395-357fe100-3472-11e9-85b4-0a5954dd451a.png)

**Comment by Sunev** [comment]
I have to say that I always create rooms by pressing Enter, I don't think it needs any fix.

**Comment by uhyo** [comment]
How about adding a confirmation dialog on pressing Enter?
Just hitting Enter again would submit the form.

**Comment by Sunev** [comment]
To trigger a dialog only when Enter pressed?
Well, that would be acceptable.
