### ISSUE TITLE
Proposal modification: Players who were helped by helpers can talk to themselves during hesitation

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#515]
Uhyoさん，Hello！
I'm a Chinese player from Sunev‘s server.

I have a small suggestion：
Allow players who were helped by helpers can talk to themselves during hesitation

Players who be helped are generally not rich in game experience, and need to communicate with helpers during hesitation.

I think this can improve their gaming experience.

https://github.com/Sunev/jinrou/issues/77

Thank you！

**Comment by uhyo** [comment]
Thank you for your feedback.
I'm considering enabling self-talk during hesitation for everyone,
as there seems no significant reason for the current behavior.
