### ISSUE TITLE
生存人数に応じて残り時間が変わる

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#529]
Thanks to 箱庭さん

> 見に行きましたが、（人数+1）*10秒、20秒、30秒、50秒がありました。

**Comment by hakoniwawind** [comment]
元々は、10・30・50のみで、20秒が追加で実装された形になります。
自分の所見としては50秒は長すぎますね…スカイプ人狼なら有りかもしれませんが。

**Comment by uhyo** [comment]
倍率も10秒刻みくらいで設定可能にする感じで考えています。
