### ISSUE TITLE
A bug about Phantom and GreedyWolf

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#535]
Uhyoさん，Hello！
I'm a Chinese player from Sunev‘s server.

I just find a Bug：
At night, Phantom steal GreedyWolf‘s job
The next morning,GreedyWolf can't see his ID in list of companions werewolves,but phantom's.
In this situation,GreedyWolf will know his job has been stolen and who the phantom is.

https://github.com/Sunev/jinrou/issues/79
![image](https://user-images.githubusercontent.com/44828559/53938002-cc42d380-40e9-11e9-8a96-ffd4ba967e41.png)

Thank you!

**Comment by Sunev** [comment]
duplicate with #534
