### ISSUE TITLE
Room owner could keep buttons other than "Join Game" if he himself didn't join that EndlessYaminabe game

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#538]
https://github.com/Sunev/jinrou/issues/80
![image](https://user-images.githubusercontent.com/12387091/54087640-bfdfa480-438f-11e9-88ef-180d4731b855.png)
Like in this screenshot. Is that a good idea to hide buttons other than "Join Game" after game started?

**Comment by uhyo** [comment]
closed by ff4eac0
