### ISSUE TITLE
New roles: ドラキュラ & 吸血鬼の眷属

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#544]
https://twitter.com/uhyo_/status/1108746254635266054
https://www65.atwiki.jp/jinro_party/pages/68.html
https://www65.atwiki.jp/jinro_party/pages/69.html

- ヴァンパイアとドラキュラは互いに把握不可

**Comment by hakoniwawind** [comment]
人狼パーティー→月下人狼移植まとめ
名前：吸血鬼→ドラキュラ
陣営：特殊→ヴァンパイア（吸血鬼？）陣営
占い結果：村人→ヴァンパイア
霊能結果：村人
襲撃耐性：なし
終了時カウント：人間1→ヴァンパイア1（ケミカルでV×ドラ,ドラ×ドラで2？）
欠け：なし→なし（身代わりセーフティの人外に該当か）
勝利条件：ドラキュラの生存且つ生存中の吸血された人（ドラキュラを含む）が過半数を超えた時点で単独勝利→加えて通常のヴァンパイア勝利でもOK（過半数を超えていないが人狼や狐の全滅且つドラキュラ（ヴァンパイア）カウント≧人間カウントで勝利）

能力：概ねwikiの通り
　　　初日行動不可。
　　　朝一に次のログが公開「吸血鬼が吸血に成功/失敗しました」
　　　このログは吸血鬼が全滅していても失敗しましたと表示され続ける
　　　剣豪（罠師）や侍の能力でも死亡する。
　　　吸血された人が把握できる。（吸血された人は吸血されているかどうかは不明）

その他気になるところ
・文面通りの仕様にすると未コピーも吸血不可、悪魔くんは吸血可能
・ドラキュラの生存とあるが、妖狐生存（狐憑きになっても）していても勝利条件は満たせるため、冒涜は弾かなくても問題はない？
・ドラキュラが全滅且つ吸血された人が過半数を超え、さらにヴァンパイアが生存している場合は？
・人狼パーティーでは小悪魔（悪女）が吸血鬼を指定すると、誘えませんでした。みたいなログが出るが（吸血鬼は恋ペアになれない仕様）月下人狼では恋ペア有りか。
・吸血鬼はお互い吸血鬼を認識できる（会話は不可）→ヴァンパイアは認識できないが、他のドラキュラは認識できるか
・複数の吸血鬼が居る場合も人狼の襲撃と同様に、吸血先は一人のみ→月下ではどうするか？


吸血鬼の眷属
・ドラキュラが把握できる→ドラキュラ及びヴァンパイアが把握できる？ごちゃまぜにして吸血鬼は〇〇ですになる？？
・人狼パーティーでは初期吸血されていない扱い
