### ISSUE TITLE
Suggest: automatically reset the player's readiness if the room had spent a long time before start.

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#545]
If the time between the first player and the last player clicked 【ready】 was greater than a certain length, remind the room owner or the system to automatically reset the player's readiness, when the owner clicks the gamestart button.

**Comment by uhyo** [comment]
:+1: though implementation would be  a little bit cumbersome?

**Comment by hakoniwawind** [comment]
idea
https://twitter.com/uhyo_/status/1109286358671982592
https://twitter.com/hakoniwawind/status/1109286735064649728
