### ISSUE TITLE
The tip of minimum number of player is inconsistent with expectations

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#565]
Uhyoさん, Hello!
I'm a Chinese player from Sunev's server.

I think I may have found a interface bug

When I use "以相同设定建立新房间"(Create a new room with the same settings) and inherit settings of an endless mode game, game start interface will remind me "人数不足。这个配置的人数最低为*人。"（The number of player is insufficient. The minimum number of player in this configuration is *person.）
The * equivalent to the number of player at the beginning of the previous room.

But even if the number of player in the tip is insufficient, the game can start as long as the number of player is actually greater than or equal to six.

So this may just be a tip that should not exist

![image](https://user-images.githubusercontent.com/44828559/58567038-30e27a00-8264-11e9-9684-f86703ac8eb4.png)

Thank you!

**Comment by uhyo** [comment]
Thank you for the report! I believe this is a bug of the UI.
