### ISSUE TITLE
Wanderingguard will be remind 100 times when no corpse was found in the morning

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#581]
Uhyoさん，Hello again！

My friend just encountered a bug.

When a Wanderingguard guard a character and no corpse was found in next morning,
Wanderingguard will be remind 100 times "○○は○○をもう護衛できません。"(○○ 不能护卫 ○○。←in Chinese）And the game is more slowly than before.

this is the screenshot.

![image](https://user-images.githubusercontent.com/44828559/61214189-d29d2800-a739-11e9-96ba-9599507ef872.png)

I don't know if it only happens on Sunevさん's server.

Thank you !

**Comment by uhyo** [comment]
That's a crazy bug... thank you!
Could you share the URL of that game?

**Comment by hakoniwawind** [comment]
https://github.com/Sunev/jinrou/issues/108

**Comment by YagamiMirai** [comment]
> Sunev#108
> https://www.werewolf.com.cn/room/88893

Thank you hakoniwawindさん!
Because the Great Firewall, I can't reply to the room link in time, sorry about that.

**Comment by hakoniwawind** [comment]
https://jinrou.uhyohyo.net/room/149870
https://jinrou.uhyohyo.net/room/149871
再現した事例としなかった事例
