### ISSUE TITLE
a Werewolf×Werewolf will be treated as two surviving wolves in Chemical Mode？

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#582]
Uhyoさん，Hello again！

(Yes, it is me again——I hope I won't bother you.)

I encountered a situation that I didn’t understand in the chemical mode today.

There is 4 players live at dawn:
Witch × Ninja
Diviner × illusionist
greedywolf × fascinatingwolf
frankensteinsmonster × tinyfox

Then announced the victory of Fox.
But there are two human, a werewolf and a fox... game should not end here, right?
The only explanation is that it will be treated as two surviving wolves.
I don't know is this a bug or a feature?

link:https://www.werewolf.com.cn/room/89071

Appreciate your help in answering my question
Thank you!

**Comment by uhyo** [comment]
This is a feature.
Yes, a Werewolf×Werewolf has a special skill that it counts as 2 werewolves.
