### ISSUE TITLE
New Role: 課金者

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#590]
from ねじれ天国

http://nejiten.halfmoon.jp/?cmd=doc#296

- 持ち投票数の概念をどうするか？
- ガチャの設定が大変（`jobstrength`をそのまま使うのは微妙か）

**Comment by hakoniwawind** [comment]
本家の確率を調べてみました。
https://docs.google.com/spreadsheets/d/1yvd0qct-sND-XdoI2MsV_koTn8PNt5NLYmjvhafbV0U

スプレッドシートに書いてますが、
・フランケンシュタイン+コピーで王様を無限にコピーして無限にガチャを引いて無限に役職変化みたいな遊びが懸念点（ #374 ）
・村人陣営以外にも★0概念としてチョコレートみたいなのは出すとか？
　（村人陣営判定がそれくらいしかないかもしれないのでどっちでも良い）

ガチャ設定は、
・jobstrengthをそれ用に見直す
・sharedに★1～5まで配列を用意する（今後役職追加する度に埋めていく必要がある）
くらいでしょうか。
