### ISSUE TITLE
A little bug in tutorial game

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#592]
Uhyoさん，Hello again！

There is an insignificant little problem in the tutorial room.
（I didn't find tutorial room on Japanese server，but Sunevさん wants me to submit it to you.）

Whether or not the player has set an avatar, An avatar display location will be reserved next to the player name.
![image](https://user-images.githubusercontent.com/44828559/63074886-07cbae80-bf62-11e9-82a9-981c6b11f1c4.png)
（”鱼儿测试用“is my alt account without avatar）

On the Day2 the player is taught to vote, but he can vote for himself.
And Scapegoats will vote for the player’s target by default, so the player is executed..
![image](https://user-images.githubusercontent.com/44828559/63075111-09e23d00-bf63-11e9-9f4a-7ad5fe76f025.png)

And then, Although the player has been executed, He can still experience the skills of the diviner.
![image](https://user-images.githubusercontent.com/44828559/63075149-3ac27200-bf63-11e9-9cbc-ea744d457424.png)

On the Day3,The player is dead, but can vote.
![image](https://user-images.githubusercontent.com/44828559/63075179-562d7d00-bf63-11e9-9722-ea02f5653543.png)

The Scapegoat that will automatically vote for the player will fail to vote.
![image](https://user-images.githubusercontent.com/44828559/63075269-a573ad80-bf63-11e9-9276-33d379c5091b.png)

Thank you!

**Comment by uhyo** [comment]
Thanks for the report!
Yeah, this feature is not yet released to the JP server.
