### ISSUE TITLE
Proposal modification: When all players die, the game will wait for the hunter to select the shooting target before ending.

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#609]
Uhyoさん，Hello again！

I have a small suggestion：

When all villagers die following the queenspectator , while the non-human side will die at the same time (for various reasons)，If there is a hunter (or madhunter, speculation), it will cause the hunter must select the target before the game is settled as a draw. And Hunter cannot choose because they are all dead.So the player must wait for the countdown to end.

![image](https://user-images.githubusercontent.com/44828559/64077609-a860f300-cd04-11e9-994e-f63cfca2b59d.png)
(When hunter click the "Select" under the "Please select a shooting target", he will be remind "This player does not exist")

I think it would be better if the player didn't have to wait.

By the way, I encountered this problem in the Chemical mode(Although I think it has nothing to do with this).

https://github.com/Sunev/jinrou/issues/111
https://www.werewolf.com.cn/room/92351

Thank you！

**Comment by uhyo** [comment]
Thank you for reporting. Indeed this isn't a good behavior...
