### ISSUE TITLE
In Chemical Mode，a Raven×AbsoluteWolf(displayed as Raven teams) will not die when other werewolves survive

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#617]
Uhyoさん，Hello again！

I encountered a situation that I didn’t understand in the chemical mode today.

My job is Raven×AbsoluteWolf that display as Raven teams。
![image](https://user-images.githubusercontent.com/44828559/65345535-15cdb880-dc0d-11e9-8231-947c06a9d1dc.png)

On the third day，Most players voted for me when my werewolf teammate is still alive。
I think I will be executed，but no…
After the game, I went back to the game record.
The system information suggests that“鱼家小店的偶像鱼儿大人 凭借自身的绝对实力抵抗了 处刑。”（AbsoluteWolf’s skill tips）

I thought that the AbsoluteWolf only triggers skill when he in werewolf teams.
So I don't know is this a bug or a feature?

My English is not good enough, so if there is a misnomer, then please forgive

link：
https://github.com/Sunev/jinrou/issues/115
https://www.werewolf.com.cn/room/93224

Appreciate your help in answering my question
Thank you!

**Comment by uhyo** [comment]
Thanks to 箱庭さん, this bug is fixed by #618.
