### ISSUE TITLE
戦績の集計がおかしい？

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#621]
https://twitter.com/risya_ag/status/1178879203212529664

**Comment by hakoniwawind** [comment]
https://twitter.com/risya_ag/status/1179026845263466496
勘違いみたいです。

自分のアカウントでも確認しましたが、問題なし
勝敗数と対戦数は引き分けもあるので必ずしもイコールではないです

**Comment by uhyo** [comment]
ありがとうございます、大丈夫そうですね。
