### ISSUE TITLE
開始即終了したゲームがルーム一覧に残る

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#623]
https://jinrou.uhyohyo.net/room/153665

レースコンディションが起こっていそう
「終了」を書き込んだあとに「対戦中」を書き込んでいる気がする

**Comment by hakoniwawind** [comment]
即終了だと、 #532 と同じ現象かもしれませんね。

**Comment by uhyo** [comment]
確かに同じっぽいですね、ありがとうございます。
