### ISSUE TITLE
ファンが死亡しているのにも関わらず、増える場合がある

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#630]
https://jinrou.uhyohyo.net/room/154777

4d夜、アイドルのファンが死亡しているのにも関わらず、新たなファンが決定される。
魔女の蘇生薬→アイドルのファンを増やすとなったためか。

ドキュメントでは、以下の文言が記載。
>自身のファンが生存している状態で4日目の夜を迎えた場合、自身と既にファンになっている人以外の生存者からランダムに1人選ばれ、自身のファンになります。

**Comment by uhyo** [comment]
ありがとうございます。仕様でもバグでもいいんですが、ランダムだとしたら良くないですね（？）
