### ISSUE TITLE
The Save button does not appear when change only the avatar

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#631]
Uhyoさん，Hello again！

This time it’s just a small bug.

In the user page, I clicked the "アイコンを選択" button and changed the avatar. But at this time the "変更を保存" button does not appear.
![image](https://user-images.githubusercontent.com/44828559/68264902-6b5b0900-0085-11ea-9cb1-bf76ca989a3f.png)

If I want to save my avatar, I have to click the "編集" button first, and the "変更を保存" button will appear.
![image](https://user-images.githubusercontent.com/44828559/68264938-86c61400-0085-11ea-9a2d-96eab589b952.png)

Although it is not troublesome, it seems to be somewhat illogical.
Is it more reasonable if the "変更を保存" button appears automatically when I change the avatar, or if I need to click "編集" button before modify the avatar?

link：(Chinese version)
https://github.com/Sunev/jinrou/issues/121

Thank you!

**Comment by uhyo** [comment]
Hmm, the icon edit seems to be buggy... thank you!
