### ISSUE TITLE
GreedyWolf×Streamer retired and become Human×Streamer

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#643]
In [this room](https://www.werewolf.com.cn/room/101516), player 鱼家小店的偶像鱼儿大人 (GreedyWolf×Streamer) lost all her Listeners. The retirement was announced, yet she became Human×Streamer instead of Greedy Wolf×Human.
![image](https://user-images.githubusercontent.com/12387091/73549971-ae5b2b80-447e-11ea-868d-7021ad64f198.png)

**Comment by uhyo** [comment]
Ohh, my code wasn't cosidering Chemical mode.
Thank you very much!
