### ISSUE TITLE
観戦者で勝敗情報がカウントされる

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#650]
https://jinrou.uhyohyo.net/room/158729
エンドレス闇鍋で参加を決定した上で参戦前に試合が終わると、下図のように勝敗がカウントされる。

![Screenshot_20200218-150059~01](https://user-images.githubusercontent.com/42696493/74708438-c5ac5e00-525f-11ea-94e1-2564495f42df.png)

**Comment by uhyo** [comment]
ありがとうございます :slightly_smiling_face:
