### ISSUE TITLE
盗まれたことに気づかず、突然死が発生してしまう

### ISSUE THREAD

**Issue by hakoniwawind** [uhyo/jinrou#653]
https://jinrou.uhyohyo.net/room/159344
ニートを盗まれた場合、無投票で突然死が発生する
#296 で変えてもらったのですが、不味い事例が起きてしまいました。orz

**Comment by uhyo** [comment]
ありがとうございます、怪盗に盗まれても突然死しない能力は例外的に消えずに残る形で修正します。
