### ISSUE TITLE
Confliction with document

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#66]
[フランケンシュタインの怪物](http://jinrou-doc.uhyohyo.net/jobs/FrankensteinsMonster.html) says, 
>以下の能力は吸収できません。
...
貴族が奴隷を身代わりにする能力
奴隷が貴族の身代わりになる能力

However [this](https://github.com/uhyo/jinrou/blob/master/server/rpc/game/game.coffee#L2896) would make FrankensteinsMonster sacrificed for Noble. Which would you like to change, code or document?

**Comment by uhyo** [comment]
I think the document should be changed since that description was due to technical limitations, if I remember correctly.
I'll do it. Thank you.
