### ISSUE TITLE
配信者の日替わり能力が使えない

### ISSUE THREAD

**Issue by silver433** [uhyo/jinrou#674]
ケミカル人狼の闇鍋で配信者を引いた時、配信者が右側に配役されている場合は日替わり能力が使えないようです。
陣営に関わらず不発になっているようなので、不具合ではないでしょうか。

参考
https://jinrou.uhyohyo.net/room/176658
https://jinrou.uhyohyo.net/room/177072
https://jinrou.uhyohyo.net/room/177179

![32372D50-B433-43A2-8F9C-043011F7196E](https://user-images.githubusercontent.com/57870190/90346482-37753100-e064-11ea-9d3c-d22dc6e240a9.jpeg)

**Comment by uhyo** [comment]
ありがとうございます、右側の能力が使えないのはバグだと思われます。

**Comment by uhyo** [comment]
修正しました ✅
