### ISSUE TITLE
Reincarnator accidentally revive the xianfox in chemical mode 

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#742]
Uhyoさん，Hello again！
（Yes it's me again…）

This time I am here to submit a question behalf of another player: 

In chemical mode, when a Reincarnator die, he can revive a Troublemaker×Xianfox. 

We speculate that this may be related to chemical mode, the reincarnator does not judge the player's second job in chemical mode. 

I don't know is this a bug or a feature?

link:
https://github.com/Sunev/jinrou/issues/161
https://www.werewolf.com.cn/room/171777

**Comment by uhyo** [comment]
Hello, thank you for reporting this! 😃 and sorry for late response.
I consider this as a bug, given that the original intent of that restriction is to support Villager team.
I will prepare a fix for this.
