### ISSUE TITLE
MinionSelector won't die when he choose a PsychoKiller

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#745]
Uhyoさん，Hello again！
（Yes it's me again and again…）

I ran into a problem today:

In the room settings, wolfminion is set to "on", and The MinionSelector selects PsychoKiller as wolfminion.

When I saw that the target was PsychoKiller, I thought I was going to die, but I was not dead at dawn the next day.

I checked the documentation of PsychoKiller, (https://jinrou-doc.uhyohyo.net/jobs/psychokiller)
And it did not indicate that its skill is invalid for MinionSelector. 

I don't know is this a bug or a feature?

**Comment by YagamiMirai** [comment]
link:
https://github.com/Sunev/jinrou/issues/162
https://www.werewolf.com.cn/room/172442

**Comment by hakoniwawind** [comment]
個人的には、ならず者と同じ扱いで良いかなと思いました。

**Comment by uhyo** [comment]
Thanks for reporting this 🙂 
As Hakoniwa san said, I'd like to consider the current implementation as a right one. Being killed just for selecting PsychoKiller is too severe.
Let us fix the docs 🙂
