### ISSUE TITLE
When the bloodwolf cast the blood moon, the player cursed by Spellcaster will not be able to speak for an additional day. 

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#748]
Uhyoさん，Hello again and again and again！
（Sorry I have submitted a lot of issues recently …）

A player told me that he encountered a situation ：
He was cursed at night by a Spellcaster, and then he couldn't speak the next day. And during the day on this day, a bloodwolf blew himself up, triggering a blood moon.
So the day came on the third day, and he still couldn't speak.

I think this may be the unexpected extension of the inability to speak effect caused by the blood moon. 
Maybe this is a little bug？

BTW：
Recently, there is a problem with the endless mode frequently: after dawn, the timer stops at the last time 0:00 (usually 0:00 night, there will be hesitation 0:00), and the game cannot continue normally.

https://jinrou.uhyohyo.net/room/201127
https://www.werewolf.com.cn/room/172719
https://www.werewolf.com.cn/room/172717
https://www.werewolf.com.cn/room/172738
Including but not limited to the above rooms have this problem. 
I have temporarily reminded players of Sunev's server not to play endless mode games for now.

**Comment by uhyo** [comment]
Thank you for reporting this 🙂 bug reports are always helpful.
I think this is a bug, and Hakoniwa san already provided a fix. :tada:

As for the endless mode problem, a deeper investigation would be needed. Give me some time.

**Comment by uhyo** [comment]
The endless mode problems is fixed too now 🙂
