### ISSUE TITLE
In chemical mode, a Streamer on the right side can't try skills

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#752]
Uhyoさん，Hello！

I think I may once again found a new bug with Streamer 

In chemical mode, a Streamer on the right side （like 村人×配信者）can't try skills even if the listener stays alive .

This seems to be a bug that existed a long time.

BTW: It seems that even if there is pyrotechnic or blood moon, the Streamer will be prompted to try the skills. But I forgot to take a screenshot of this one.

**Comment by uhyo** [comment]
Thanks for reporting this and sorry for late reply 🥺 Fixed!
