### ISSUE TITLE
Two sacrifices cause the game to enter an endless loop 

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#754]
Uhyoさん，I'm here again！

Two sacrifice release skills to each other, then one of them is about to die. 
So they continued to sacrifice for each other…
So the game got stuck. 

![QQ截图20210914144938](https://user-images.githubusercontent.com/44828559/133212114-438d2a7e-530b-4f92-a44c-3e196597afba.png)
(【○○为了守护○○而甘愿成为活祭品。】means【○○が○○を守るため自らの命を差し出そうとしています。】）

![image](https://user-images.githubusercontent.com/44828559/133212334-68156167-d534-4e8e-9622-b431a36fd389.png)
（they continued to sacrifice for each other）

![image](https://user-images.githubusercontent.com/44828559/133212716-769bb5d1-31b5-4044-9c49-6c9b19e1ec4f.png)
（A System message when Gamemaster try to add some time)

link:
https://www.werewolf.com.cn/room/173942
https://github.com/Sunev/jinrou/issues/169 (Chinese version)

I think it might be possible to circumvent this problem by making the effect of the sacrifice invalid on another sacrifice …

**Comment by uhyo** [comment]
Thank you for reporting this, this is serious 😨

And also thank you Hakoniwa san for fixing this so quickly 🙂
