### ISSUE TITLE
Dark psychic failed to kill hunter

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#796]
Uhyoさん，久しぶりだな！

Here's a new little problem:

After darkpsychic was voted to death, the hunter did not die that night.

I think this should be a bug…

link:
https://www.werewolf.com.cn/room/216770
https://github.com/Sunev/jinrou/issues/186

**Comment by uhyo** [comment]
@YagamiMirai Hi, thank you for reporting this 🙂 
I think Hakoniwa san gave it a fix. I will re-check that the issue is fixed.
