### ISSUE TITLE
Handle "mixed content" problem

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#84]
When using HTTPS, loading HTTP contents is called "mixed content" and is considered not secure.
In our service it occurs mainly because users' icons are served using HTTP.
We need to automatically switch to HTTPS as much as possible.

**Comment by Sunev** [comment]
If i have not misunderstood, [642cfa0](https://github.com/uhyo/jinrou/commit/642cfa086b482eb9890977ede121ed42a131c64e) has done something as same as
> `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

Quotes from [here](http://thehackernews.com/2015/04/disable-mixed-content-warning.html)
This could lead to an awkward situation: some user's picture links do not support https access.
I'd like to suggest some "adviced site" while users enter an icon link.

**Comment by uhyo** [comment]
I didn't know that. But there is a difference between `Content-Security-Policy: upgrade-insecure-requests` and our implementation.
When an icon is not available via HTTPS, CSP does not fall back to HTTP but ours falls back, still causing a mixed content error.
I know that the best way in view of security is to not allow HTTP icons but I took backward compatibility for now.

Suggesting icon uploading site is quite hard, but showing an advice to use an HTTPS site is nice.
