### ISSUE TITLE
Penalty for 突然死

### ISSUE THREAD

**Issue by uhyo** [uhyo/jinrou#86]
The upgraded blacklist system may enable automatic limitation to user who did 突然死 several times.

**Comment by Sunev** [comment]
About this, I had developed a featrue which acts as followig:

1. Set a uplimit for Sudden Death Punishment, like 360 minutes.
2. After a game comes to be End, server will check if there exists some event of `"gone-day"` or `"gone-night"`.
3. Divide that uplimit by `players.length`, which maybe like 12 or some.
4. Show all players of this room a checkbox list of Sudden Dead Players and ask a vote.
5. Each player should make a decision about wether he/she would like a Sudden Dead Player got punished.
6. Every vote will become a punishment as long as `Math.floor(uplimit/players.length)` minutes.

These means a Sudden Dead Player will be blocked for, at most, like 6 hours. Or will not be punished when forgave by all other player.

**Comment by uhyo** [comment]
Awesome!
Can this be a pull request?

**Comment by Sunev** [comment]
I'm glad to make it into a pull request, but it may need some time.
It was about two years ago, when I was too young to understand Branch is necessary.

**Comment by uhyo** [comment]
No problem. I look forward to see your pull request, but you don't need to hurry.
Actually I'm busy now and may take time to evaluate or respond.
